name: Deploy to Cloud Provider
on:
  workflow_call:
    inputs:
      provider:
        description: 'Cloud provider to deploy to (google or aws)'
        required: true
        type: string
      ambiente:
        description: 'Environment to deploy to (dev, staging, prod)'
        required: true
        type: string
      manifest:
        description: 'Path to the Kubernetes manifest file'
        required: true
        type: string
      image_tag:
        description: 'Docker image tag to use for deployment'
        required: true
        type: string
jobs:
  deploy:
    environment: ${{ inputs.ambiente }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --------------------
      # Google Cloud
      # --------------------
      - name: Subistitue imagem no manifest
        if: ${{ inputs.provider == 'google' }}
        run: |
          echo "Substituindo a imagem no manifest ${inputs.manifest} com a tag ${inputs.image_tag}"
          sed -i "s|image:.*|image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dev-repo-gke/app-image:${{ inputs.image_tag }}|g" ${{ inputs.manifest }}

      - name: Autenticate with Google Cloud
        if: ${{ inputs.provider == 'google' }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to GKE
        if: ${{ inputs.provider == 'google' }}
        uses: google-github-actions/deploy-gke@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_LOCATION }}
          manifest: ${{ inputs.manifest }}
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dev-repo-gke/app-image:${{ inputs.image_tag }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}


      # --------------------
      # AWS EKS
      # --------------------
      - name: Authenticate with AWS
        if: ${{ inputs.provider == 'aws'}}
        run: |
          echo "Aqui estamos simulando a autenticação com o AWS no ambiente ${{ inputs.ambiente }}"
          echo "aws_access_key_id: ${{ secrets.aws_access_key_id }}"
          echo "aws_secret_access_key: ${{ secrets.aws_secret_access_key }}"

      - name: Set up AWS CLI
        if: ${{ inputs.provider == 'aws'}}
        run: |
          echo "Aqui estamos configurando o AWS CLI para o ambiente ${{ inputs.ambiente }}"
          echo "Project ID: ${{ secrets.project_id }}"
          echo "Region: ${{ secrets.region }}"
          echo "Cluster Name: ${{ secrets.cluster_name }}"
          echo "Manifest Path: ${{ inputs.manifest }}"
          echo "Deploying to AWS EKS..."
