name: Deploy to Cloud Provider
on:
  workflow_call:
    inputs:
      ambiente:
        description: 'Environment to deploy to (dev, staging, prod)'
        required: true
        type: string
      manifests:
        description: 'Path to Kubernetes manifests for deployment'
        required: true
        type: string
      image_tag:
        description: 'Docker image tag to use for deployment'
        required: true
        type: string
jobs:
  deploy:
    environment: ${{ inputs.ambiente }}
    runs-on: ubuntu-latest
    steps:
      # --------------------
      # DIGITAL OCEAN KUBERNETES
      # --------------------
      - name: Validando recebimento do ambiente
        run: |
          echo "Ambiente: ${{ inputs.ambiente }}"
          echo "Kubeconfig: ${{ secrets.KUBECONFIG }}"

      - name: Set Kube Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Digital Ocean
        uses: azure/k8s-deploy@v5
        with:
          manifests: ${{ inputs.manifests }}
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/kube-news:${{ inputs.image_tag }}
          namespace: ${{ secrets.CONFIG_NAMESPACE }}
